# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Ci-CD process

on:
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: carnival-azurefunction-demo # set this to your function app name on Azure
  PACKAGE_DIRECTORY: '.' # set this to the directory which contains pom.xml file
  JAVA_VERSION: '8' # set this to the java version to use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello World
      run: echo "Hello, World int he build!"

  deploy-to-qa:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: QA

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Display Environment Name
      run: echo "Deploying to QA environment"

    - name: Print Hello World
      run: echo "Hello, World!"

  deploy-to-preprod:
    needs: deploy-to-qa
    runs-on: ubuntu-latest
    environment:
      name: PREPROD

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Display Environment Name
      run: echo "Deploying to PREPROD environment"

    - name: Print Hello World
      run: echo "Hello, World!"
          